name: shub_test_task1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5 
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  excel: ^4.0.6
  file_picker: ^8.0.5
  intl: ^0.18.1
  awesome_dialog: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
